### PR TITLE
WIP: internal.yml - adds comments on PR

### PR DESCRIPTION
**Pull request by konrad-sol**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by konrad-sol** [comment]
UI tests status: success

**Comment by konrad-sol** [comment]
UI tests status: failure

**Comment by konrad-sol** [comment]
**UI tests status: success**
Branch used: refs/pull/63/merge
Triggered by: pull_request (konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1494358386)

**Comment by konrad-sol** [comment]
**UI tests status: success**
Branch used: refs/heads/test/add_comments_in_PR
Triggered by: push (konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1494358235)

**Comment by konrad-sol** [comment]
**UI tests status: success**
Branch used: refs/pull/63/merge
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1494371291)

**Comment by konrad-sol** [comment]
**UI tests status: success**
Branch used: refs/heads/test/add_comments_in_PR
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1494371150)

**Comment by konrad-sol** [comment]
**UI tests status: failure**
Branch used: refs/heads/test/add_comments_in_PR
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1494371150)

**Comment by konrad-sol** [comment]
**UI tests status: failure** ${STATUS} 
Branch used: refs/heads/test/add_comments_in_PR
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1495804218)

**Comment by konrad-sol** [comment]
**UI tests status: failure** ${STATUS} 
Branch used: refs/pull/63/merge
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1495804553)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1495820988)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1495821102)

**Comment by konrad-sol** [comment]
test comment

**Comment by maciejwojciechowski** [comment]
comment

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Commit: update
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520428465)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Commit: 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520428671)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Commit: 
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520475830)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Commit: 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520475900)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Commit: update or 323fd84ec71b0f5a2859e83842272c90d7603468
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520487324)

**Comment by konrad-sol** [comment]
**UI tests status: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Commit:  or 323fd84ec71b0f5a2859e83842272c90d7603468
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520487454)

**Comment by konrad-sol** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Commit: 5ed0755877cadea1c505b26870ed2115cbe02550 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520675900)

**Comment by konrad-sol** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Commit: 5ed0755877cadea1c505b26870ed2115cbe02550 fixes in PR comment
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520675835)

**Comment by konrad-sol** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/63/merge
Commit: 0999f858527c6b22ccef2e961389b92660c4c632 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520740353)

**Comment by konrad-sol** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR
Commit: 0999f858527c6b22ccef2e961389b92660c4c632 pick test
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520740228)

**Pull request closed without merging**
