### PR TITLE
refactor federation test

### PR DESCRIPTION
**Pull request by konrad-sol**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/180/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6122407014)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/test/refactor_another_oas_test
Commit: 8dfd5278144c5eafbc07b3d695210aaa73f0b8d7 refactor federation test
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6122404896)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/180/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6122407017)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/refactor_another_oas_test
Commit: d9180d599144fedf6d437e72db48436a8b6d5ee0 increase timeout
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6123298143)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/180/merge
Commit: d9180d599144fedf6d437e72db48436a8b6d5ee0 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6123298759)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/180/merge
Commit: d9180d599144fedf6d437e72db48436a8b6d5ee0 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6123298758)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/180/merge
Commit: 79526f9d1a1b8432bdc72fe1dbe7dd7110821024 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6298330968)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/refactor_another_oas_test
Commit: 79526f9d1a1b8432bdc72fe1dbe7dd7110821024 increase timeout for graphql test
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6298330475)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/180/merge
Commit: 79526f9d1a1b8432bdc72fe1dbe7dd7110821024 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6298330966)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 0dc480ed740fb0c1a06db9467520f2663c7f6e4c refactor federation test
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6298503496)

**Comment by buger** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 0dc480ed740fb0c1a06db9467520f2663c7f6e4c refactor federation test
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6298503493)

**Pull request merged**
