### PR TITLE
New tests for schema editor in federation

### PR DESCRIPTION
**Pull request by behcio**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/145/merge
Commit:  
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3823241213)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/145/merge
Commit: f2680768d8d0598f305d40705be12c62368ca15f 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3824137017)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/145/merge
Commit: 214fa52f034abeec6851e985c345670942a203fe 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3827727104)

**Review by konrad-sol — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: e547e364194bbf724fcccb66d7da264c32e5c35a New tests for schema editor in federation
Triggered by: push (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3829152595)

**Pull request merged**
