### PR TITLE
Updated .gitignore and udg tests

### PR DESCRIPTION
**Pull request by behcio**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/189/merge
Commit:  
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6431118730)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/189/merge
Commit:  
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6431118732)

**Review by konrad-sol — APPROVED** [review]

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ec8d69da94379e57c785b54114ded0caa1d3939b Updated .gitignore and udg tests
Triggered by: push (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6432169220)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ec8d69da94379e57c785b54114ded0caa1d3939b Updated .gitignore and udg tests
Triggered by: push (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6432169212)

**Pull request merged**
