### PR TITLE
add PR comments in CI

### PR DESCRIPTION
**Pull request by konrad-sol**
## Description
Addin one more step in internal.yml for comments on PRs

## Checklist

- [x] Make sure that tests are passing in githubaction
- [x] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [x] Tests are stable

### CODE REVIEW

**Comment by konrad-sol** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/67/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1520765492)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/67/merge
Commit: 9e8630ee2ad239061d1d83ce640ccbfc19c44a8f 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1582057709)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR_v2
Commit: 9e8630ee2ad239061d1d83ce640ccbfc19c44a8f change name of secret for comments PR in CI
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1582057583)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_comments_in_PR_v2
Commit: 6d9b58ce9618613a7fe8b9ec62e3bd7f25f0ffbf refactor federation running method
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1630026270)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/67/merge
Commit: 6d9b58ce9618613a7fe8b9ec62e3bd7f25f0ffbf 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1630026290)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 8a43fde423a367823fad4c87b89c9f6542f6537c add PR comments in CI
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1630075642)

**Pull request merged**
