### PR TITLE
fix OAS endpoint designer tests

### PR DESCRIPTION
**Pull request by maciejwojciechowski**
## Checklist

- [x] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/130/merge
Commit:  
Triggered by: pull_request (@maciejwojciechowski)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3563843009)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/130/merge
Commit: f4f8580545c57194a35ddae8fff25c812cee07f0 
Triggered by: pull_request (@maciejwojciechowski)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3563848749)

**Review by konrad-sol — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 73184ff20a9ad9ca5e794933a49a140179393fc6 fix endpoint designer tests
Triggered by: push (@maciejwojciechowski)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3564085636)

**Pull request merged**
