### PR TITLE
Federation ci changes

### PR DESCRIPTION
**Pull request by behcio**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/140/merge
Commit:  
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3694818960)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/140/merge
Commit: dd581a16568711d5e7dc9c6c956e48064b8da844 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3695034025)

**Review by konrad-sol — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/140/merge
Commit: e2cfbe2f76645ccddfe0f49d8333fb9f0f061db0 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3730224627)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: c938ece3a3160d3b1558a74d46482f64154b0566 Federation to be launched from docker compose
Triggered by: push (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/3730660116)

**Pull request merged**
