### PR TITLE
Keys id crud

### PR DESCRIPTION
**Pull request by kolavcic**
## Description

Refactored test to work in playwright framework

## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by buger** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/191/merge
Commit:  
Triggered by: pull_request (@kolavcic)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6462422863)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/191/merge
Commit:  
Triggered by: pull_request (@kolavcic)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6462422865)

**Comment by buger** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/191/merge
Commit:  
Triggered by: pull_request (@kolavcic)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6462422863)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/191/merge
Commit: db954f73f21cf830f566fd51df127e774252b3e6 
Triggered by: pull_request (@kolavcic)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6462569234)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/191/merge
Commit: db954f73f21cf830f566fd51df127e774252b3e6 
Triggered by: pull_request (@kolavcic)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6462569228)

**Review by konrad-sol — APPROVED** [review]

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 869df1800a7eb719b67dd393f5e087fef5b95858 Test refactor to TS
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6466330233)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 869df1800a7eb719b67dd393f5e087fef5b95858 Test refactor to TS
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/6466330222)

**Pull request merged**
