### PR TITLE
Added UDG test for internal datasources

### PR DESCRIPTION
**Pull request by behcio**
## Checklist

- [ ] Make sure that tests are passing in githubaction
- [ ] Check if change should be populated to other branches (master, release-3-lts, release-4.0)
- [ ] Tests are stable

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/87/merge
Commit: 2de3b99753676fa9dab1cc555075be0e9fc41d28 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1876836004)

**Review by konrad-sol — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 514b3a7a1e98e66c449b770dbc9b3e896618383a Added UDG test for internal datasources
Triggered by: push (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1881847530)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit:  
Triggered by: workflow_dispatch (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1886740621)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 514b3a7a1e98e66c449b770dbc9b3e896618383a Added UDG test for internal datasources
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk-analytics-tests/actions/runs/1881847530)

**Pull request merged**
